# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "hyperv" do |h|
    h.vmname = "kraken-manager"
    h.memory = 2048

    config.vm.network "public_network"
    config.vm.synced_folder ".", "/vagrant", type: "smb", disabled: false

    h.vm_integration_services = {
      guest_service_interface: true
    }
  end

  config.vm.provision "shell", inline: "apt update"
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt upgrade -y -q --with-new-pkgs"
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt install -y -q python3-pip"
  config.vm.provision "shell", inline: "pip3 install ansible"
  config.vm.provision "shell", inline: "hostnamectl set-hostname kraken-manager"

end
