version: '3.5'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - "38080:80"
    networks: 
      - kraken

networks:
  kraken:
    external: true

    