version: '3.5'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: password
    expose: 
      - "80"
    ports:
      - "5432:80"
    networks: 
      - kraken_backend

networks:
  kraken_backend:
    external: true

    