version: "3.5"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    #ports: 
    #  - "5432:5432"
    networks: 
      - kraken

networks:
  kraken: